export const CMSLocators = {
    cmsClientId: '//input[@id="clientid"]',
    cmsUsername: '//input[@id="username"]',
    cmsPassword: '//input[@id="password"]',
    cmsLoginButton: '//input[@value="Login"]',
    showcaseIcon: '//li[@class="nav-showcase"]/a',
    deleteDataBtn: '//span[text()="Delete Data"]',
    emailIdInput: '//input[@id="data_email_id"]',
    deleteUserBtn: '//button[@name="userjson"]',
    deletedMsg: '//p[text()="Deleted Successfully"]',
    mobile_num_input: '//input[@id="data_mobile_no"]'
};

export const GTWebsiteLocators = {
    // GT login locators
    login_button: "//a[@title='Login/Registration link']",
    mobile_number: "//input[@name='Mobile Number']",
    send_otp: "(//span[normalize-space()='Send OTP'])[1]",
    resend_otp: "//span[normalize-space()='Resend OTP']",
    enter_otp: "(//input[@id='loginMobOtpverification'])[1]",
    verify_otp: "//span[contains(text(),'Verify')]",
    desclaimer: "(//span[@class='checkmark'])[1]",
    acknowledge: "(//span[@class='checkmark'])[2]",
    invalid_login_button: "//button[contains(@class,'btn-login')]",
    login_form_button: "(//button[@class='btn-site btn-login'])[1]",
    invalid_dob_message: "//span[contains(text(),'The Date of Birth must be between 1950-01-01 and 2')]",
    invalid_mob_no_message: "//span[normalize-space()='Invalid Mobile Number']",
    field_is_required: "//span[normalize-space()='Field is required']",
    invalid_jersey_no_message: "//span[contains(text(),'The Jersey Number field may not be greater than 3 ')]",
    time_remaining: "//span[@class='time']",
    attempts: "//span[@class='globalMsg']",
    verification_pending_message: "//span[normalize-space()='Field is required']",
    terms_and_conditions: "//a[@title='Read our terms and conditions']",
    verify_terms_and_conditions: "//span[normalize-space()='Terms and Conditions']",
    profile_page_url: "https://stg-gujarat-titans.sportz.io/profile",
    select_country_code: "//button[@class='selected-title']",
    get_country_list: "//div[@class='select-list']//div[@class='list-wrapper']//button[@class='list-item'][.//p[contains(text(), '{}')]]",

    // GT create profile locators
    first_name: "(//input[@id='firstName'])[1]",
    last_name: "(//input[@id='lastName'])[1]",
    email: "//input[@id='registerEmail']",
    date_of_birth: "//input[@id='regDob']",
    country: "//button[@aria-label='country']",
    get_list: "//div[@class='list-item']//span[normalize-space()='{}']",
    state: "//button[@aria-label='state']",
    city: "//button[@aria-label='city']",
    zip_code: "//input[@id='regZipCode']",
    gender: "document.getElementById('regGenderMale').click()",
    jersey_no: "//input[@id='regJerseyNumber']",
    jersey_name: "//input[@id='regJerseyName']",
    referrel_code: "//input[@name='referralCode']",
    favourite_player: "//select[@name='Favourite Player']",
    submit_button: "//button[@class='btn-site btn-register']",
    css_submit_button: "button[class='btn-site btn-register'] span[class='btn-text']",
    fname_field_err_msg: "//div[@class='form-group flex50 reg-fname']//span[@class='errordiv'][normalize-space()='Field is required']",
    lname_field_err_msg: "//div[@class='form-group flex50 reg-lname']//span[@class='errordiv'][normalize-space()='Field is required']",
    profile_masthead_card: "//div[@class='profile-masthead-card']",
    setting: "//span[normalize-space()='Setting']",
    edit_profile: "//span[normalize-space()='edit profile']",
    complete_profile: "//p[@class='profile-title']",

    // GT Verify profile elements
    verify_email: "input[placeholder='Enter your Email']",
    verify_dob: "//input[@placeholder='Enter your date of birth']",
    verify_mob_no: "//input[@id='regMobile']",
    verify_country: "//select[@id='Country']",
    verify_city: "//input[@id='city']",
    verify_zipcode: "//input[@id='zipCode']",
    verify_jersey_name: "//input[@id='jerseyName']",
    verify_jersey_no: "//input[@id='jerseyNumber']",
    verify_male_selected: "//input[@id='regGenderMale']",
    verify_female_selected: "//input[@id='regGenderFemale']",
    verify_other_selected: "//input[@id='regGenderOther']",
    verify_gender: "//input[@name='Gender']",
    invalid_mail: "//span[normalize-space()='Invalid email']",

    js_dob: "input[placeholder='Enter your date of birth']",
    js_mob_no: "return document.getElementById('regMobile').value;",
    js_country: 'return document.querySelector("#Country option:checked").text;',
    js_zopcode: "return document.getElementById('zipCode').value;",
    js_jersey_name: "return document.getElementById('jerseyName').value;",
    js_jersey_no: "return document.getElementById('jerseyNumber').value;",

    // verify points
    css_signup_points: "div[class='points'] span[class='text']",
    gt_rewards: "//span[@class='text'][normalize-space()='GT Rewards']",
    open_menu: "//button[@aria-label='Open User Menu']",
    veiw_profile: "//a[normalize-space()='View Profile']",
    logout: "//div[@class='user-action']//button[contains(@class, 'user-logout')]//span[normalize-space()='Logout']",
    button_transaction: "//button[@aria-label='Transactions']",
    available_balance: "//span[@class='points-data']",
    rewards_page: "(//span[@class='text'][normalize-space()='GT Rewards'])[2]",
    transacions1: "(//div[@class='activity-description'])[1]",
    transacions_key: "//div[contains(@class, 'table-data activity')]",
    transacions_value: "//div[contains(@class, 'table-data credit')]/span",
    news: "//span[normalize-space()='News']",
    read_news: "document.querySelector('.article-item a').click();",
    css_news1: ".article-item a",
    photos: "//span[normalize-space()='Photos']",

    // Keys to be validate
    update_profile_key: "Points awarded for updating profile",
    reading_article_key: "Points awarded for reading article",
    referring_a_friend_key: "Points awarded for referring a friend"
};